---
- name: Install and configure Nginx web server on Amazon Linux
  hosts: webservers-nginx
  become: yes
  tasks:
    - name: Update yum cache
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install nginx from amazon-linux-extras
      shell: |
        sudo yum install nginx -y

    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled at boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy a basic index.html
      copy:
        content: "<html><body><h1>Nginx is working on EC2!</h1></body></html>"
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

